# Generated by Django 4.0.5 on 2022-09-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
